require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.cmp"
require "user.lsp"
require "user.trouble"
require "user.telescope"
require "user.lualine"
require "user.bufferline"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.nvim-tree"
require "user.alpha"
require "user.gitsigns"

-- TODO: lazy loading
require "user.crates"
